baseurl = "https://www.adamdubey.github.io"
title = "adamdubey.github.io"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

# Google Analytics
googleAnalytics = "UA-136386310-1"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
    author = "Adam Dubey"
    info = "Intergalactic citizen of the Internet."
    description = "Adam's personal website"
    keywords = "blog,developer,engineer"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/imgages/favicon-16x16.png"

    footercontent = "☮️ ♥️ 🌎"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    #custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/adamdubey/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/adam-dubey/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "projects/"
